/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reproductor.vistas.paneles;

import com.reproductor.modelo.Reproductor;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author operador
 */
public class pnlCanciones extends javax.swing.JPanel {

    Reproductor mi_reproductor = new Reproductor();
    public pnlCanciones() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReproductorInterno = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        pnlNorteR = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        pnlSurR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNMusica = new javax.swing.JLabel();
        labelArtista = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        pnlCentralR = new javax.swing.JPanel();
        pnlEcualizador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlFondoOpcion = new javax.swing.JPanel();
        pnlIngreso = new javax.swing.JPanel();
        pnlIngresoNorte = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelConsultarPI = new javax.swing.JLabel();
        labelCrearPI = new javax.swing.JLabel();
        pnlIngresoSur = new javax.swing.JPanel();
        reproductor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelNMusica1 = new javax.swing.JLabel();
        labelArtista1 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        btnAtras1 = new javax.swing.JButton();
        btnPlay1 = new javax.swing.JButton();
        pnlIngresoCentro = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        Artista = new javax.swing.JLabel();
        cmbArtista = new javax.swing.JComboBox<>();
        labelGenero = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        labelAlbum = new javax.swing.JLabel();
        txtAlbum = new javax.swing.JTextField();
        labelDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JFormattedTextField();
        labelUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        BtnCargarImagen = new com.reproductor.modelo.MaterialButtomRectangle();
        BtnCargarMusica = new com.reproductor.modelo.MaterialButtomRectangle();
        BtnGuardar = new com.reproductor.modelo.MaterialButtomRectangle();
        btnEliminar = new com.reproductor.modelo.MaterialButtomRectangle();
        btnCargar = new com.reproductor.modelo.MaterialButtomRectangle();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_cancion = new javax.swing.JTable();

        pnlReproductorInterno.setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlNorteR.setBackground(new java.awt.Color(18, 18, 18));
        pnlNorteR.setPreferredSize(new java.awt.Dimension(663, 32));

        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
        labelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlNorteRLayout = new javax.swing.GroupLayout(pnlNorteR);
        pnlNorteR.setLayout(pnlNorteRLayout);
        pnlNorteRLayout.setHorizontalGroup(
            pnlNorteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorteRLayout.createSequentialGroup()
                .addGap(0, 681, Short.MAX_VALUE)
                .addComponent(labelExit))
        );
        pnlNorteRLayout.setVerticalGroup(
            pnlNorteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorteRLayout.createSequentialGroup()
                .addComponent(labelExit)
                .addGap(0, 0, 0))
        );

        jPanel1.add(pnlNorteR, java.awt.BorderLayout.PAGE_START);

        pnlSurR.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(40, 40, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imagen");

        labelNMusica.setBackground(new java.awt.Color(0, 0, 0));
        labelNMusica.setText("NOMBRE DE LA MUSICA");

        labelArtista.setBackground(new java.awt.Color(0, 0, 0));
        labelArtista.setText("ARTISTA");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/siguiente.png"))); // NOI18N
        btnSiguiente.setToolTipText("");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setEnabled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/anterior.png"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setEnabled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/pausa.png"))); // NOI18N
        btnPlay.setToolTipText("");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSurRLayout = new javax.swing.GroupLayout(pnlSurR);
        pnlSurR.setLayout(pnlSurRLayout);
        pnlSurRLayout.setHorizontalGroup(
            pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurRLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        pnlSurRLayout.setVerticalGroup(
            pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurRLayout.createSequentialGroup()
                .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSurRLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSurRLayout.createSequentialGroup()
                                .addComponent(labelNMusica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelArtista))
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );

        jPanel1.add(pnlSurR, java.awt.BorderLayout.PAGE_END);

        pnlCentralR.setBackground(new java.awt.Color(0, 204, 255));
        pnlCentralR.setMinimumSize(new java.awt.Dimension(200, 250));
        pnlCentralR.setPreferredSize(new java.awt.Dimension(663, 230));
        pnlCentralR.setLayout(new java.awt.BorderLayout());

        pnlEcualizador.setBackground(new java.awt.Color(18, 18, 18));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/radio.gif"))); // NOI18N

        javax.swing.GroupLayout pnlEcualizadorLayout = new javax.swing.GroupLayout(pnlEcualizador);
        pnlEcualizador.setLayout(pnlEcualizadorLayout);
        pnlEcualizadorLayout.setHorizontalGroup(
            pnlEcualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEcualizadorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlEcualizadorLayout.setVerticalGroup(
            pnlEcualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEcualizadorLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, 0))
        );

        pnlCentralR.add(pnlEcualizador, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlCentralR, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlReproductorInternoLayout = new javax.swing.GroupLayout(pnlReproductorInterno.getContentPane());
        pnlReproductorInterno.getContentPane().setLayout(pnlReproductorInternoLayout);
        pnlReproductorInternoLayout.setHorizontalGroup(
            pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlReproductorInternoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlReproductorInternoLayout.setVerticalGroup(
            pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
            .addGroup(pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlReproductorInternoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(24, 24, 24));
        setPreferredSize(new java.awt.Dimension(1200, 710));

        pnlFondoOpcion.setBackground(new java.awt.Color(204, 51, 255));
        pnlFondoOpcion.setPreferredSize(new java.awt.Dimension(1200, 710));

        pnlIngreso.setBackground(new java.awt.Color(255, 51, 102));
        pnlIngreso.setPreferredSize(new java.awt.Dimension(1129, 491));
        pnlIngreso.setLayout(new java.awt.BorderLayout());

        pnlIngresoNorte.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoNorte.setPreferredSize(new java.awt.Dimension(862, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icon_canciones.png"))); // NOI18N
        jLabel23.setToolTipText("Qué significa la opción Mis accesos Rápidos?");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Canciones");

        labelConsultarPI.setBackground(new java.awt.Color(0, 0, 0));
        labelConsultarPI.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelConsultarPI.setForeground(new java.awt.Color(255, 255, 255));
        labelConsultarPI.setText("Consultar");
        labelConsultarPI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarPIMouseClicked(evt);
            }
        });

        labelCrearPI.setBackground(new java.awt.Color(0, 0, 0));
        labelCrearPI.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelCrearPI.setForeground(new java.awt.Color(29, 185, 84));
        labelCrearPI.setText("Crear");
        labelCrearPI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearPIMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlIngresoNorteLayout = new javax.swing.GroupLayout(pnlIngresoNorte);
        pnlIngresoNorte.setLayout(pnlIngresoNorteLayout);
        pnlIngresoNorteLayout.setHorizontalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresoNorteLayout.createSequentialGroup()
                .addContainerGap(892, Short.MAX_VALUE)
                .addComponent(labelCrearPI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConsultarPI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIngresoNorteLayout.setVerticalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlIngresoNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCrearPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelConsultarPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlIngreso.add(pnlIngresoNorte, java.awt.BorderLayout.PAGE_START);

        pnlIngresoSur.setBackground(new java.awt.Color(102, 51, 255));
        pnlIngresoSur.setPreferredSize(new java.awt.Dimension(862, 64));

        reproductor.setBackground(new java.awt.Color(18, 18, 18));

        jLabel2.setBackground(new java.awt.Color(40, 40, 40));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Imagen");

        labelNMusica1.setBackground(new java.awt.Color(0, 0, 0));
        labelNMusica1.setForeground(new java.awt.Color(255, 255, 255));
        labelNMusica1.setText("NOMBRE DE LA MUSICA");

        labelArtista1.setBackground(new java.awt.Color(0, 0, 0));
        labelArtista1.setForeground(new java.awt.Color(255, 255, 255));
        labelArtista1.setText("ARTISTA");

        btnSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/siguiente.png"))); // NOI18N
        btnSiguiente1.setToolTipText("");
        btnSiguiente1.setBorderPainted(false);
        btnSiguiente1.setContentAreaFilled(false);
        btnSiguiente1.setEnabled(false);
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });

        btnAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/anterior.png"))); // NOI18N
        btnAtras1.setToolTipText("");
        btnAtras1.setBorderPainted(false);
        btnAtras1.setContentAreaFilled(false);
        btnAtras1.setEnabled(false);
        btnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras1ActionPerformed(evt);
            }
        });

        btnPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/play.png"))); // NOI18N
        btnPlay1.setToolTipText("");
        btnPlay1.setBorderPainted(false);
        btnPlay1.setContentAreaFilled(false);
        btnPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reproductorLayout = new javax.swing.GroupLayout(reproductor);
        reproductor.setLayout(reproductorLayout);
        reproductorLayout.setHorizontalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(btnAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        reproductorLayout.setVerticalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reproductorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(reproductorLayout.createSequentialGroup()
                                .addComponent(labelNMusica1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelArtista1))
                            .addComponent(btnPlay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtras1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlIngresoSurLayout = new javax.swing.GroupLayout(pnlIngresoSur);
        pnlIngresoSur.setLayout(pnlIngresoSurLayout);
        pnlIngresoSurLayout.setHorizontalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reproductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlIngresoSurLayout.setVerticalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoSurLayout.createSequentialGroup()
                .addComponent(reproductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnlIngreso.add(pnlIngresoSur, java.awt.BorderLayout.PAGE_END);

        pnlIngresoCentro.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoCentro.setPreferredSize(new java.awt.Dimension(1200, 600));

        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre");

        Artista.setForeground(new java.awt.Color(255, 255, 255));
        Artista.setText("Artista");

        cmbArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Artista" }));
        cmbArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArtistaActionPerformed(evt);
            }
        });

        labelGenero.setForeground(new java.awt.Color(255, 255, 255));
        labelGenero.setText("GENERO");

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Genero" }));
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });

        labelAlbum.setForeground(new java.awt.Color(255, 255, 255));
        labelAlbum.setText("ALBUM");

        labelDuracion.setForeground(new java.awt.Color(255, 255, 255));
        labelDuracion.setText("DURACIÓN");

        txtDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtDuracion.setText("##:##");
        txtDuracion.setToolTipText("Minutos:Segundos");

        labelUrl.setForeground(new java.awt.Color(255, 255, 255));
        labelUrl.setText("URL");

        txtUrl.setEnabled(false);

        lblFoto.setBackground(new java.awt.Color(51, 0, 51));

        BtnCargarImagen.setBackground(new java.awt.Color(29, 185, 84));
        BtnCargarImagen.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargarImagen.setText("Imagen");

        BtnCargarMusica.setBackground(new java.awt.Color(29, 185, 84));
        BtnCargarMusica.setForeground(new java.awt.Color(255, 255, 255));
        BtnCargarMusica.setText("musica");

        BtnGuardar.setBackground(new java.awt.Color(29, 185, 84));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("guardar");

        btnEliminar.setBackground(new java.awt.Color(29, 185, 84));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("eLIMINAR");

        btnCargar.setBackground(new java.awt.Color(29, 185, 84));
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("CARGAR");

        pnlTabla.setBackground(new java.awt.Color(18, 18, 18));

        jScrollPane2.setBorder(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 650));

        tb_cancion.setBackground(new java.awt.Color(18, 18, 18));
        tb_cancion.setForeground(new java.awt.Color(29, 185, 84));
        tb_cancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_cancion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_cancion.setSelectionBackground(new java.awt.Color(29, 185, 84));
        jScrollPane2.setViewportView(tb_cancion);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlIngresoCentroLayout = new javax.swing.GroupLayout(pnlIngresoCentro);
        pnlIngresoCentro.setLayout(pnlIngresoCentroLayout);
        pnlIngresoCentroLayout.setHorizontalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Artista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(cmbGenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbArtista, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUrl)
                            .addComponent(txtDuracion)
                            .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(403, 403, 403))
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCargarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlIngresoCentroLayout.setVerticalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresoCentroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Artista)
                            .addComponent(cmbArtista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenero)
                            .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAlbum)
                            .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDuracion)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUrl)
                            .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCargarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pnlIngreso.add(pnlIngresoCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlFondoOpcionLayout = new javax.swing.GroupLayout(pnlFondoOpcion);
        pnlFondoOpcion.setLayout(pnlFondoOpcionLayout);
        pnlFondoOpcionLayout.setHorizontalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE))
        );
        pnlFondoOpcionLayout.setVerticalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed

    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void cmbArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArtistaActionPerformed

    }//GEN-LAST:event_cmbArtistaActionPerformed

    private void labelConsultarPIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarPIMouseClicked
       

    }//GEN-LAST:event_labelConsultarPIMouseClicked

    private void labelCrearPIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearPIMouseClicked
        
    }//GEN-LAST:event_labelCrearPIMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked

        
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exih.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseExited

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtras1ActionPerformed

    private void btnPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlay1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Artista;
    public com.reproductor.modelo.MaterialButtomRectangle BtnCargarImagen;
    public com.reproductor.modelo.MaterialButtomRectangle BtnCargarMusica;
    public com.reproductor.modelo.MaterialButtomRectangle BtnGuardar;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnAtras1;
    public com.reproductor.modelo.MaterialButtomRectangle btnCargar;
    public com.reproductor.modelo.MaterialButtomRectangle btnEliminar;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnPlay1;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JButton btnSiguiente1;
    public javax.swing.JComboBox<String> cmbArtista;
    public javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAlbum;
    public javax.swing.JLabel labelArtista;
    public javax.swing.JLabel labelArtista1;
    public javax.swing.JLabel labelConsultarPI;
    public javax.swing.JLabel labelCrearPI;
    private javax.swing.JLabel labelDuracion;
    public javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelGenero;
    public javax.swing.JLabel labelNMusica;
    public javax.swing.JLabel labelNMusica1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelUrl;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlCentralR;
    private javax.swing.JPanel pnlEcualizador;
    public javax.swing.JPanel pnlFondoOpcion;
    public javax.swing.JPanel pnlIngreso;
    public javax.swing.JPanel pnlIngresoCentro;
    public javax.swing.JPanel pnlIngresoNorte;
    public javax.swing.JPanel pnlIngresoSur;
    private javax.swing.JPanel pnlNorteR;
    public javax.swing.JDialog pnlReproductorInterno;
    private javax.swing.JPanel pnlSurR;
    public javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel reproductor;
    public javax.swing.JTable tb_cancion;
    public javax.swing.JTextField txtAlbum;
    public javax.swing.JFormattedTextField txtDuracion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
