/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reproductor.vistas.paneles;

import com.reproductor.modelo.Reproductor;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author operador
 */
public class pnlEscuchadasR extends javax.swing.JPanel {

    Reproductor mi_reproductor = new Reproductor();
    public pnlEscuchadasR() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReproductorInterno = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        pnlNorteR = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        pnlSurR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNMusica = new javax.swing.JLabel();
        labelArtista = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        pnlCentralR = new javax.swing.JPanel();
        pnlEcualizador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlFondoOpcion = new javax.swing.JPanel();
        pnlIngreso = new javax.swing.JPanel();
        pnlIngresoNorte = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnlIngresoSur = new javax.swing.JPanel();
        pnlIngresoCentro = new javax.swing.JPanel();
        jlbMensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        pnlReproductorInterno.setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlNorteR.setBackground(new java.awt.Color(18, 18, 18));
        pnlNorteR.setPreferredSize(new java.awt.Dimension(663, 32));

        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
        labelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlNorteRLayout = new javax.swing.GroupLayout(pnlNorteR);
        pnlNorteR.setLayout(pnlNorteRLayout);
        pnlNorteRLayout.setHorizontalGroup(
            pnlNorteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorteRLayout.createSequentialGroup()
                .addGap(0, 681, Short.MAX_VALUE)
                .addComponent(labelExit))
        );
        pnlNorteRLayout.setVerticalGroup(
            pnlNorteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorteRLayout.createSequentialGroup()
                .addComponent(labelExit)
                .addGap(0, 0, 0))
        );

        jPanel1.add(pnlNorteR, java.awt.BorderLayout.PAGE_START);

        pnlSurR.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(40, 40, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imagen");

        labelNMusica.setBackground(new java.awt.Color(0, 0, 0));
        labelNMusica.setText("NOMBRE DE LA MUSICA");

        labelArtista.setBackground(new java.awt.Color(0, 0, 0));
        labelArtista.setText("ARTISTA");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/siguiente.png"))); // NOI18N
        btnSiguiente.setToolTipText("");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setEnabled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/anterior.png"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setEnabled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/pausa.png"))); // NOI18N
        btnPlay.setToolTipText("");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSurRLayout = new javax.swing.GroupLayout(pnlSurR);
        pnlSurR.setLayout(pnlSurRLayout);
        pnlSurRLayout.setHorizontalGroup(
            pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurRLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        pnlSurRLayout.setVerticalGroup(
            pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurRLayout.createSequentialGroup()
                .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSurRLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSurRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlSurRLayout.createSequentialGroup()
                                .addComponent(labelNMusica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelArtista))
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );

        jPanel1.add(pnlSurR, java.awt.BorderLayout.PAGE_END);

        pnlCentralR.setBackground(new java.awt.Color(0, 204, 255));
        pnlCentralR.setMinimumSize(new java.awt.Dimension(200, 250));
        pnlCentralR.setPreferredSize(new java.awt.Dimension(663, 230));
        pnlCentralR.setLayout(new java.awt.BorderLayout());

        pnlEcualizador.setBackground(new java.awt.Color(18, 18, 18));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/radio.gif"))); // NOI18N

        javax.swing.GroupLayout pnlEcualizadorLayout = new javax.swing.GroupLayout(pnlEcualizador);
        pnlEcualizador.setLayout(pnlEcualizadorLayout);
        pnlEcualizadorLayout.setHorizontalGroup(
            pnlEcualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEcualizadorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlEcualizadorLayout.setVerticalGroup(
            pnlEcualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEcualizadorLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, 0))
        );

        pnlCentralR.add(pnlEcualizador, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlCentralR, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlReproductorInternoLayout = new javax.swing.GroupLayout(pnlReproductorInterno.getContentPane());
        pnlReproductorInterno.getContentPane().setLayout(pnlReproductorInternoLayout);
        pnlReproductorInternoLayout.setHorizontalGroup(
            pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlReproductorInternoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlReproductorInternoLayout.setVerticalGroup(
            pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
            .addGroup(pnlReproductorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlReproductorInternoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(24, 24, 24));
        setPreferredSize(new java.awt.Dimension(1200, 710));

        pnlFondoOpcion.setBackground(new java.awt.Color(18, 18, 18));
        pnlFondoOpcion.setPreferredSize(new java.awt.Dimension(1200, 710));

        pnlIngreso.setBackground(new java.awt.Color(255, 51, 102));
        pnlIngreso.setPreferredSize(new java.awt.Dimension(1129, 491));
        pnlIngreso.setLayout(new java.awt.BorderLayout());

        pnlIngresoNorte.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoNorte.setPreferredSize(new java.awt.Dimension(862, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icon_canciones.png"))); // NOI18N
        jLabel23.setToolTipText("Qué significa la opción Mis accesos Rápidos?");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Canciones");

        javax.swing.GroupLayout pnlIngresoNorteLayout = new javax.swing.GroupLayout(pnlIngresoNorte);
        pnlIngresoNorte.setLayout(pnlIngresoNorteLayout);
        pnlIngresoNorteLayout.setHorizontalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresoNorteLayout.createSequentialGroup()
                .addContainerGap(1070, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIngresoNorteLayout.setVerticalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlIngreso.add(pnlIngresoNorte, java.awt.BorderLayout.PAGE_START);

        pnlIngresoSur.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoSur.setPreferredSize(new java.awt.Dimension(862, 50));

        javax.swing.GroupLayout pnlIngresoSurLayout = new javax.swing.GroupLayout(pnlIngresoSur);
        pnlIngresoSur.setLayout(pnlIngresoSurLayout);
        pnlIngresoSurLayout.setHorizontalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlIngresoSurLayout.setVerticalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlIngreso.add(pnlIngresoSur, java.awt.BorderLayout.PAGE_END);

        pnlIngresoCentro.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoCentro.setPreferredSize(new java.awt.Dimension(1200, 600));

        jlbMensaje.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlIngresoCentroLayout = new javax.swing.GroupLayout(pnlIngresoCentro);
        pnlIngresoCentro.setLayout(pnlIngresoCentroLayout);
        pnlIngresoCentroLayout.setHorizontalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                        .addComponent(jlbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                        .addGap(400, 400, 400))))
        );
        pnlIngresoCentroLayout.setVerticalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresoCentroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        pnlIngreso.add(pnlIngresoCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlFondoOpcionLayout = new javax.swing.GroupLayout(pnlFondoOpcion);
        pnlFondoOpcion.setLayout(pnlFondoOpcionLayout);
        pnlFondoOpcionLayout.setHorizontalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE))
        );
        pnlFondoOpcionLayout.setVerticalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked

        try {
            mi_reproductor.Stop();
        } catch (Exception ex) {
            Logger.getLogger(pnlEscuchadasR.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.pnlReproductorInterno.dispose();
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exih.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseExited

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel jlbMensaje;
    public javax.swing.JLabel labelArtista;
    public javax.swing.JLabel labelExit;
    public javax.swing.JLabel labelNMusica;
    private javax.swing.JPanel pnlCentralR;
    private javax.swing.JPanel pnlEcualizador;
    public javax.swing.JPanel pnlFondoOpcion;
    public javax.swing.JPanel pnlIngreso;
    public javax.swing.JPanel pnlIngresoCentro;
    public javax.swing.JPanel pnlIngresoNorte;
    public javax.swing.JPanel pnlIngresoSur;
    private javax.swing.JPanel pnlNorteR;
    public javax.swing.JDialog pnlReproductorInterno;
    private javax.swing.JPanel pnlSurR;
    // End of variables declaration//GEN-END:variables
}
