    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reproductor.vistas.paneles;

import com.reproductor.modelo.Reproductor;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author operador
 */
public class pnlHome extends javax.swing.JPanel {

    Reproductor mi_reproductor = new Reproductor();
    public pnlHome() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaReproduccion = new javax.swing.JDialog();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_canciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlFondoOpcion = new javax.swing.JPanel();
        pnlIngreso = new javax.swing.JPanel();
        pnlIngresoNorte = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnlIngresoSur = new javax.swing.JPanel();
        reproductor = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        labelNMusica = new javax.swing.JLabel();
        labelArtista = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        pnlIngresoCentro = new javax.swing.JPanel();
        pnlListas = new javax.swing.JPanel();
        labelFavorito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlInternoRep = new javax.swing.JPanel();
        pnlFavoritos = new javax.swing.JPanel();
        labelFavorito1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlInternoFav = new javax.swing.JPanel();
        pnlRecientes = new javax.swing.JPanel();
        labelFavorito2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlInternoRep1 = new javax.swing.JPanel();

        pnlTabla.setBackground(new java.awt.Color(18, 18, 18));

        jScrollPane4.setBorder(null);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(452, 650));

        tb_canciones.setBackground(new java.awt.Color(18, 18, 18));
        tb_canciones.setForeground(new java.awt.Color(29, 185, 84));
        tb_canciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_canciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_canciones.setSelectionBackground(new java.awt.Color(29, 185, 84));
        jScrollPane4.setViewportView(tb_canciones);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Reproducción");

        javax.swing.GroupLayout ListaReproduccionLayout = new javax.swing.GroupLayout(ListaReproduccion.getContentPane());
        ListaReproduccion.getContentPane().setLayout(ListaReproduccionLayout);
        ListaReproduccionLayout.setHorizontalGroup(
            ListaReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaReproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
            .addGroup(ListaReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ListaReproduccionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ListaReproduccionLayout.setVerticalGroup(
            ListaReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaReproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(ListaReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ListaReproduccionLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(24, 24, 24));
        setPreferredSize(new java.awt.Dimension(1200, 710));

        pnlFondoOpcion.setBackground(new java.awt.Color(204, 51, 255));
        pnlFondoOpcion.setPreferredSize(new java.awt.Dimension(1200, 800));

        pnlIngreso.setBackground(new java.awt.Color(255, 51, 102));
        pnlIngreso.setPreferredSize(new java.awt.Dimension(1129, 491));
        pnlIngreso.setLayout(new java.awt.BorderLayout());

        pnlIngresoNorte.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoNorte.setPreferredSize(new java.awt.Dimension(862, 50));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icon_canciones.png"))); // NOI18N
        jLabel23.setToolTipText("Qué significa la opción Mis accesos Rápidos?");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Home");

        javax.swing.GroupLayout pnlIngresoNorteLayout = new javax.swing.GroupLayout(pnlIngresoNorte);
        pnlIngresoNorte.setLayout(pnlIngresoNorteLayout);
        pnlIngresoNorteLayout.setHorizontalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresoNorteLayout.createSequentialGroup()
                .addContainerGap(1070, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIngresoNorteLayout.setVerticalGroup(
            pnlIngresoNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlIngreso.add(pnlIngresoNorte, java.awt.BorderLayout.PAGE_START);

        pnlIngresoSur.setBackground(new java.awt.Color(102, 51, 255));
        pnlIngresoSur.setPreferredSize(new java.awt.Dimension(862, 80));

        reproductor.setBackground(new java.awt.Color(53, 53, 53));
        reproductor.setPreferredSize(new java.awt.Dimension(1200, 80));

        labelImagen.setBackground(new java.awt.Color(40, 40, 40));
        labelImagen.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelNMusica.setBackground(new java.awt.Color(0, 0, 0));
        labelNMusica.setForeground(new java.awt.Color(255, 255, 255));
        labelNMusica.setText("NOMBRE DE LA MUSICA");

        labelArtista.setBackground(new java.awt.Color(0, 0, 0));
        labelArtista.setForeground(new java.awt.Color(255, 255, 255));
        labelArtista.setText("ARTISTA");

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/siguiente.png"))); // NOI18N
        btnSiguiente.setToolTipText("");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/anterior.png"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/reproductor/play.png"))); // NOI18N
        btnPlay.setToolTipText("");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnSiguiente2.setToolTipText("");
        btnSiguiente2.setBorderPainted(false);
        btnSiguiente2.setContentAreaFilled(false);
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reproductorLayout = new javax.swing.GroupLayout(reproductor);
        reproductor.setLayout(reproductorLayout);
        reproductorLayout.setHorizontalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(btnSiguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        reproductorLayout.setVerticalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reproductorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(reproductorLayout.createSequentialGroup()
                        .addComponent(labelNMusica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelArtista))
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSiguiente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pnlIngresoSurLayout = new javax.swing.GroupLayout(pnlIngresoSur);
        pnlIngresoSur.setLayout(pnlIngresoSurLayout);
        pnlIngresoSurLayout.setHorizontalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reproductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlIngresoSurLayout.setVerticalGroup(
            pnlIngresoSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoSurLayout.createSequentialGroup()
                .addComponent(reproductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnlIngreso.add(pnlIngresoSur, java.awt.BorderLayout.PAGE_END);

        pnlIngresoCentro.setBackground(new java.awt.Color(18, 18, 18));
        pnlIngresoCentro.setPreferredSize(new java.awt.Dimension(1200, 800));

        pnlListas.setBackground(new java.awt.Color(18, 18, 18));
        pnlListas.setPreferredSize(new java.awt.Dimension(1180, 210));

        labelFavorito.setBackground(new java.awt.Color(255, 255, 255));
        labelFavorito.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        labelFavorito.setForeground(new java.awt.Color(29, 185, 84));
        labelFavorito.setText("Listas Reproducción");

        jScrollPane1.setBorder(null);

        pnlInternoRep.setBackground(new java.awt.Color(18, 18, 18));
        pnlInternoRep.setLayout(new java.awt.GridLayout(1, 5));
        jScrollPane1.setViewportView(pnlInternoRep);

        javax.swing.GroupLayout pnlListasLayout = new javax.swing.GroupLayout(pnlListas);
        pnlListas.setLayout(pnlListasLayout);
        pnlListasLayout.setHorizontalGroup(
            pnlListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlListasLayout.createSequentialGroup()
                        .addComponent(labelFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlListasLayout.setVerticalGroup(
            pnlListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFavorito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFavoritos.setBackground(new java.awt.Color(18, 18, 18));
        pnlFavoritos.setPreferredSize(new java.awt.Dimension(1180, 210));

        labelFavorito1.setBackground(new java.awt.Color(255, 255, 255));
        labelFavorito1.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        labelFavorito1.setForeground(new java.awt.Color(29, 185, 84));
        labelFavorito1.setText("Favoritos");

        jScrollPane2.setBorder(null);

        pnlInternoFav.setBackground(new java.awt.Color(18, 18, 18));
        pnlInternoFav.setLayout(new java.awt.GridLayout(1, 5));
        jScrollPane2.setViewportView(pnlInternoFav);

        javax.swing.GroupLayout pnlFavoritosLayout = new javax.swing.GroupLayout(pnlFavoritos);
        pnlFavoritos.setLayout(pnlFavoritosLayout);
        pnlFavoritosLayout.setHorizontalGroup(
            pnlFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFavoritosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlFavoritosLayout.createSequentialGroup()
                        .addComponent(labelFavorito1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFavoritosLayout.setVerticalGroup(
            pnlFavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFavoritosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFavorito1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRecientes.setBackground(new java.awt.Color(18, 18, 18));
        pnlRecientes.setPreferredSize(new java.awt.Dimension(1180, 210));

        labelFavorito2.setBackground(new java.awt.Color(255, 255, 255));
        labelFavorito2.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        labelFavorito2.setForeground(new java.awt.Color(29, 185, 84));
        labelFavorito2.setText("Recientes");

        jScrollPane3.setBorder(null);

        pnlInternoRep1.setBackground(new java.awt.Color(18, 18, 18));
        pnlInternoRep1.setLayout(new java.awt.GridLayout(1, 5));
        jScrollPane3.setViewportView(pnlInternoRep1);

        javax.swing.GroupLayout pnlRecientesLayout = new javax.swing.GroupLayout(pnlRecientes);
        pnlRecientes.setLayout(pnlRecientesLayout);
        pnlRecientesLayout.setHorizontalGroup(
            pnlRecientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlRecientesLayout.createSequentialGroup()
                        .addComponent(labelFavorito2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 998, Short.MAX_VALUE))))
        );
        pnlRecientesLayout.setVerticalGroup(
            pnlRecientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFavorito2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlIngresoCentroLayout = new javax.swing.GroupLayout(pnlIngresoCentro);
        pnlIngresoCentro.setLayout(pnlIngresoCentroLayout);
        pnlIngresoCentroLayout.setHorizontalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlRecientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
                    .addComponent(pnlListas, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
                    .addComponent(pnlFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)))
        );
        pnlIngresoCentroLayout.setVerticalGroup(
            pnlIngresoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoCentroLayout.createSequentialGroup()
                .addComponent(pnlFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlRecientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlIngreso.add(pnlIngresoCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlFondoOpcionLayout = new javax.swing.GroupLayout(pnlFondoOpcion);
        pnlFondoOpcion.setLayout(pnlFondoOpcionLayout);
        pnlFondoOpcionLayout.setHorizontalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE))
        );
        pnlFondoOpcionLayout.setVerticalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ListaReproduccion;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel labelArtista;
    private javax.swing.JLabel labelFavorito;
    private javax.swing.JLabel labelFavorito1;
    private javax.swing.JLabel labelFavorito2;
    public javax.swing.JLabel labelImagen;
    public javax.swing.JLabel labelNMusica;
    public javax.swing.JPanel pnlFavoritos;
    public javax.swing.JPanel pnlFondoOpcion;
    public javax.swing.JPanel pnlIngreso;
    public javax.swing.JPanel pnlIngresoCentro;
    public javax.swing.JPanel pnlIngresoNorte;
    public javax.swing.JPanel pnlIngresoSur;
    public javax.swing.JPanel pnlInternoFav;
    public javax.swing.JPanel pnlInternoRep;
    public javax.swing.JPanel pnlInternoRep1;
    public javax.swing.JPanel pnlListas;
    public javax.swing.JPanel pnlRecientes;
    public javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel reproductor;
    public javax.swing.JTable tb_canciones;
    // End of variables declaration//GEN-END:variables
}
