/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reproductor.vistas.paneles;

import com.reproductor.modelo.Artistas;
import com.reproductor.modelo.Conexion;
import com.reproductor.vistas.Principal;
import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author operador
 */
public class pnlListaReproduccion extends javax.swing.JPanel {

    FileInputStream fis, fism;
    int logitudByte, longitudByteM;
    Artistas art = new Artistas();
    String artista_id = "";
    String valorSeleccionado;
    int idArtista = 0;
    int idGenero = 0;
    int fila;
    Conexion conexion = new Conexion();
    Principal interfaz;

    public pnlListaReproduccion() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFondoOpcion = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlAccesos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        BtnEnviar = new com.reproductor.modelo.MaterialButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCargarMusica = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaRepr = new javax.swing.JTable();
        BtnGuardar = new com.reproductor.modelo.MaterialButtomRectangle();
        BtnReset = new com.reproductor.modelo.MaterialButtomRectangle();

        setBackground(new java.awt.Color(24, 24, 24));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1290, 725));

        pnlFondoOpcion.setBackground(new java.awt.Color(24, 24, 24));
        pnlFondoOpcion.setPreferredSize(new java.awt.Dimension(385, 204));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Lista de Reproducción");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icon_list.png"))); // NOI18N
        jLabel21.setToolTipText("Qué significa la opción Mis accesos Rápidos?");

        pnlAccesos.setBackground(new java.awt.Color(24, 24, 24));
        pnlAccesos.setForeground(new java.awt.Color(204, 51, 0));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Lista");

        BtnEnviar.setBackground(new java.awt.Color(29, 185, 84));
        BtnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEnviar.setText(">");

        jScrollPane2.setBackground(new java.awt.Color(18, 18, 18));

        tblCargarMusica.setBackground(new java.awt.Color(18, 18, 18));
        tblCargarMusica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCargarMusica.setForeground(new java.awt.Color(250, 250, 250));
        tblCargarMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CD", "Canción Grabadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCargarMusica.setGridColor(new java.awt.Color(18, 18, 18));
        tblCargarMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCargarMusicaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCargarMusicaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblCargarMusica);
        if (tblCargarMusica.getColumnModel().getColumnCount() > 0) {
            tblCargarMusica.getColumnModel().getColumn(0).setMinWidth(50);
            tblCargarMusica.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblCargarMusica.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tblListaRepr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblListaRepr.setForeground(new java.awt.Color(0, 74, 140));
        tblListaRepr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Cancion Lista Reproducción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaRepr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaReprMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblListaReprMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblListaRepr);
        if (tblListaRepr.getColumnModel().getColumnCount() > 0) {
            tblListaRepr.getColumnModel().getColumn(0).setMinWidth(50);
            tblListaRepr.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblListaRepr.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        BtnGuardar.setBackground(new java.awt.Color(29, 185, 84));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");

        BtnReset.setBackground(new java.awt.Color(29, 185, 84));
        BtnReset.setForeground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("Reset");

        javax.swing.GroupLayout pnlAccesosLayout = new javax.swing.GroupLayout(pnlAccesos);
        pnlAccesos.setLayout(pnlAccesosLayout);
        pnlAccesosLayout.setHorizontalGroup(
            pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAccesosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(pnlAccesosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(pnlAccesosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAccesosLayout.setVerticalGroup(
            pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccesosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAccesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAccesosLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout pnlFondoOpcionLayout = new javax.swing.GroupLayout(pnlFondoOpcion);
        pnlFondoOpcion.setLayout(pnlFondoOpcionLayout);
        pnlFondoOpcionLayout.setHorizontalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAccesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoOpcionLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel21)
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        pnlFondoOpcionLayout.setVerticalGroup(
            pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoOpcionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlFondoOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAccesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(pnlFondoOpcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCargarMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargarMusicaMouseClicked
       
    }//GEN-LAST:event_tblCargarMusicaMouseClicked

    private void tblCargarMusicaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargarMusicaMouseReleased

    }//GEN-LAST:event_tblCargarMusicaMouseReleased

    private void tblListaReprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaReprMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaReprMouseClicked

    private void tblListaReprMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaReprMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListaReprMouseReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.reproductor.modelo.MaterialButton BtnEnviar;
    public com.reproductor.modelo.MaterialButtomRectangle BtnGuardar;
    public com.reproductor.modelo.MaterialButtomRectangle BtnReset;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPanel pnlAccesos;
    public javax.swing.JPanel pnlFondoOpcion;
    public javax.swing.JTable tblCargarMusica;
    public javax.swing.JTable tblListaRepr;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
