/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reproductor.vistas;

import com.reproductor.RepositoryController.ListRController;

import com.mancompsolutions.modelo.Dimensiones;
import com.reproductor.modelo.Artistas;
import com.reproductor.modelo.metodosGenerales;
import com.reproductor.vistas.paneles.pnlCanciones;
import com.reproductor.vistas.paneles.pnlListaReproduccion;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author operador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_intfz
     */
//variables para capturar la posicion del cursor
    int x, y;
    public metodosGenerales metodos = new metodosGenerales();
    Dimensiones dimensiones = new Dimensiones();

    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    
    
    public Principal() {
        initComponents();

    }
    
   

    public void OpenInternet() {
        try {
            Desktop.getDesktop().browse(URI.create("https://www.youtube.com/?hl=es-419"));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDAccesosDirectos = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        ContenedorPestanas = new javax.swing.JTabbedPane();
        label_Exit = new javax.swing.JLabel();
        pnl_Titulo = new javax.swing.JPanel();
        LabelTitulo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelAccesosR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JDAccesosDirectos1 = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        label_Exit1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        LabelTitulo1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnlFondo = new javax.swing.JPanel();
        pnlEste = new javax.swing.JPanel();
        LateralPnlNorte = new javax.swing.JPanel();
        LateralPnlCentro = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fondo1 = new javax.swing.JPanel();
        labelCanciones = new javax.swing.JLabel();
        labelReproductor = new javax.swing.JLabel();
        labelAlbunes = new javax.swing.JLabel();
        labelEReciente = new javax.swing.JLabel();
        labelCFavoritas = new javax.swing.JLabel();
        labelBiblioteca = new javax.swing.JLabel();
        labelUsers = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelArtistas = new javax.swing.JLabel();
        labelHome = new javax.swing.JLabel();
        LateralPnlSur = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        labelListaReproduciones = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblConsulta = new javax.swing.JLabel();
        lblYoutube = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        Norte = new javax.swing.JPanel();
        labelNombreUsuario = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        labelMin = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        Sur = new javax.swing.JPanel();

        JDAccesosDirectos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDAccesosDirectos.setUndecorated(true);
        JDAccesosDirectos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JDAccesosDirectosFocusGained(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 74, 140), new java.awt.Color(0, 74, 140)));

        ContenedorPestanas.setBackground(new java.awt.Color(255, 255, 255));

        label_Exit.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_Exit.setForeground(new java.awt.Color(0, 74, 140));
        label_Exit.setText("X");
        label_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_ExitMousePressed(evt);
            }
        });

        pnl_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_TituloMouseDragged(evt);
            }
        });
        pnl_Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_TituloMousePressed(evt);
            }
        });

        LabelTitulo2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        LabelTitulo2.setForeground(new java.awt.Color(51, 51, 51));
        LabelTitulo2.setText("Configuración de Accesos Directos");

        javax.swing.GroupLayout pnl_TituloLayout = new javax.swing.GroupLayout(pnl_Titulo);
        pnl_Titulo.setLayout(pnl_TituloLayout);
        pnl_TituloLayout.setHorizontalGroup(
            pnl_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_TituloLayout.setVerticalGroup(
            pnl_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TituloLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Accesos Faltantes");

        LabelAccesosR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LabelAccesosR.setForeground(new java.awt.Color(51, 51, 51));
        LabelAccesosR.setText("0");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("/12");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(ContenedorPestanas)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(LabelAccesosR)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(pnl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_Exit)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Exit)
                    .addComponent(pnl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContenedorPestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelAccesosR)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout JDAccesosDirectosLayout = new javax.swing.GroupLayout(JDAccesosDirectos.getContentPane());
        JDAccesosDirectos.getContentPane().setLayout(JDAccesosDirectosLayout);
        JDAccesosDirectosLayout.setHorizontalGroup(
            JDAccesosDirectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDAccesosDirectosLayout.setVerticalGroup(
            JDAccesosDirectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDAccesosDirectosLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JDAccesosDirectos1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDAccesosDirectos1.setUndecorated(true);
        JDAccesosDirectos1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JDAccesosDirectos1FocusGained(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 74, 140), new java.awt.Color(0, 74, 140)));

        label_Exit1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_Exit1.setForeground(new java.awt.Color(0, 74, 140));
        label_Exit1.setText("X");
        label_Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_Exit1MousePressed(evt);
            }
        });

        LabelTitulo1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        LabelTitulo1.setForeground(new java.awt.Color(51, 51, 51));
        LabelTitulo1.setText("Configuración de Accesos Directos");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addComponent(label_Exit1)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(label_Exit1)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout JDAccesosDirectos1Layout = new javax.swing.GroupLayout(JDAccesosDirectos1.getContentPane());
        JDAccesosDirectos1.getContentPane().setLayout(JDAccesosDirectos1Layout);
        JDAccesosDirectos1Layout.setHorizontalGroup(
            JDAccesosDirectos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDAccesosDirectos1Layout.setVerticalGroup(
            JDAccesosDirectos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDAccesosDirectos1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlFondo.setBackground(new java.awt.Color(236, 240, 241));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        pnlEste.setLayout(new java.awt.BorderLayout());

        LateralPnlNorte.setBackground(new java.awt.Color(18, 18, 18));
        LateralPnlNorte.setPreferredSize(new java.awt.Dimension(280, 50));

        javax.swing.GroupLayout LateralPnlNorteLayout = new javax.swing.GroupLayout(LateralPnlNorte);
        LateralPnlNorte.setLayout(LateralPnlNorteLayout);
        LateralPnlNorteLayout.setHorizontalGroup(
            LateralPnlNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        LateralPnlNorteLayout.setVerticalGroup(
            LateralPnlNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlEste.add(LateralPnlNorte, java.awt.BorderLayout.PAGE_START);

        LateralPnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(204, 0, 51));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(256, 720));

        fondo1.setBackground(new java.awt.Color(18, 18, 18));
        fondo1.setPreferredSize(new java.awt.Dimension(256, 600));
        fondo1.setLayout(null);

        labelCanciones.setBackground(new java.awt.Color(255, 255, 255));
        labelCanciones.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelCanciones.setForeground(new java.awt.Color(255, 255, 255));
        labelCanciones.setText("     Canciones");
        labelCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCanciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelCancionesMouseMoved(evt);
            }
        });
        labelCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCancionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCancionesMouseExited(evt);
            }
        });
        fondo1.add(labelCanciones);
        labelCanciones.setBounds(0, 280, 280, 30);

        labelReproductor.setBackground(new java.awt.Color(255, 255, 255));
        labelReproductor.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelReproductor.setForeground(new java.awt.Color(255, 255, 255));
        labelReproductor.setText("     Reproductor");
        labelReproductor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelReproductor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelReproductorMouseMoved(evt);
            }
        });
        labelReproductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReproductorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelReproductorMouseExited(evt);
            }
        });
        fondo1.add(labelReproductor);
        labelReproductor.setBounds(0, 440, 280, 30);

        labelAlbunes.setBackground(new java.awt.Color(255, 255, 255));
        labelAlbunes.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelAlbunes.setForeground(new java.awt.Color(255, 255, 255));
        labelAlbunes.setText("     Álbumes");
        labelAlbunes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAlbunes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelAlbunesMouseMoved(evt);
            }
        });
        labelAlbunes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAlbunesMouseExited(evt);
            }
        });
        fondo1.add(labelAlbunes);
        labelAlbunes.setBounds(0, 400, 280, 30);

        labelEReciente.setBackground(new java.awt.Color(255, 255, 255));
        labelEReciente.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelEReciente.setForeground(new java.awt.Color(255, 255, 255));
        labelEReciente.setText("     Escuchad. recient.");
        labelEReciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEReciente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelERecienteMouseMoved(evt);
            }
        });
        labelEReciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelERecienteMouseExited(evt);
            }
        });
        fondo1.add(labelEReciente);
        labelEReciente.setBounds(0, 130, 280, 30);

        labelCFavoritas.setBackground(new java.awt.Color(255, 255, 255));
        labelCFavoritas.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelCFavoritas.setForeground(new java.awt.Color(255, 255, 255));
        labelCFavoritas.setText("     Canciones Favoritas");
        labelCFavoritas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCFavoritas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelCFavoritasMouseMoved(evt);
            }
        });
        labelCFavoritas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCFavoritasMouseExited(evt);
            }
        });
        fondo1.add(labelCFavoritas);
        labelCFavoritas.setBounds(0, 170, 280, 30);

        labelBiblioteca.setBackground(new java.awt.Color(255, 255, 255));
        labelBiblioteca.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        labelBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        labelBiblioteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBiblioteca.setText("     TU BIBLIOTECA");
        labelBiblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBiblioteca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelBibliotecaMouseMoved(evt);
            }
        });
        labelBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBibliotecaMouseExited(evt);
            }
        });
        fondo1.add(labelBiblioteca);
        labelBiblioteca.setBounds(0, 40, 250, 30);

        labelUsers.setBackground(new java.awt.Color(255, 255, 255));
        labelUsers.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelUsers.setForeground(new java.awt.Color(255, 255, 255));
        labelUsers.setText("     Usuarios");
        labelUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUsers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelUsersMouseMoved(evt);
            }
        });
        labelUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUsersMouseExited(evt);
            }
        });
        fondo1.add(labelUsers);
        labelUsers.setBounds(0, 240, 280, 30);

        labelGenero.setBackground(new java.awt.Color(255, 255, 255));
        labelGenero.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(255, 255, 255));
        labelGenero.setText("     Generos");
        labelGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelGenero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelGeneroMouseMoved(evt);
            }
        });
        labelGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGeneroMouseExited(evt);
            }
        });
        fondo1.add(labelGenero);
        labelGenero.setBounds(0, 360, 280, 30);

        labelArtistas.setBackground(new java.awt.Color(255, 255, 255));
        labelArtistas.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelArtistas.setForeground(new java.awt.Color(255, 255, 255));
        labelArtistas.setText("     Artistas");
        labelArtistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelArtistas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelArtistasMouseMoved(evt);
            }
        });
        labelArtistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelArtistasMouseExited(evt);
            }
        });
        fondo1.add(labelArtistas);
        labelArtistas.setBounds(0, 320, 280, 30);

        labelHome.setBackground(new java.awt.Color(255, 255, 255));
        labelHome.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        labelHome.setForeground(new java.awt.Color(29, 185, 84));
        labelHome.setText("     Home");
        labelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelHomeMouseMoved(evt);
            }
        });
        labelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelHomeMouseExited(evt);
            }
        });
        fondo1.add(labelHome);
        labelHome.setBounds(0, 80, 280, 50);

        jScrollPane3.setViewportView(fondo1);

        javax.swing.GroupLayout LateralPnlCentroLayout = new javax.swing.GroupLayout(LateralPnlCentro);
        LateralPnlCentro.setLayout(LateralPnlCentroLayout);
        LateralPnlCentroLayout.setHorizontalGroup(
            LateralPnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(LateralPnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );
        LateralPnlCentroLayout.setVerticalGroup(
            LateralPnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(LateralPnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pnlEste.add(LateralPnlCentro, java.awt.BorderLayout.CENTER);

        LateralPnlSur.setBackground(new java.awt.Color(18, 18, 18));
        LateralPnlSur.setPreferredSize(new java.awt.Dimension(280, 90));

        labelListaReproduciones.setBackground(new java.awt.Color(255, 255, 255));
        labelListaReproduciones.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelListaReproduciones.setForeground(new java.awt.Color(255, 255, 255));
        labelListaReproduciones.setText("     Lista Reproduccion");
        labelListaReproduciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelListaReproducionesMouseMoved(evt);
            }
        });
        labelListaReproduciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelListaReproducionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelListaReproducionesMouseExited(evt);
            }
        });

        lblConsulta.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lblConsulta.setForeground(new java.awt.Color(255, 255, 255));
        lblConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icons8_Search_30px.png"))); // NOI18N
        lblConsulta.setToolTipText("Consultar Datos");
        lblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaMouseClicked(evt);
            }
        });

        lblYoutube.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYoutube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/icons8_YouTube_30px_1.png"))); // NOI18N
        lblYoutube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout LateralPnlSurLayout = new javax.swing.GroupLayout(LateralPnlSur);
        LateralPnlSur.setLayout(LateralPnlSurLayout);
        LateralPnlSurLayout.setHorizontalGroup(
            LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralPnlSurLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(labelListaReproduciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LateralPnlSurLayout.createSequentialGroup()
                        .addComponent(lblYoutube, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LateralPnlSurLayout.setVerticalGroup(
            LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralPnlSurLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LateralPnlSurLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelListaReproduciones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LateralPnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYoutube, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );

        pnlEste.add(LateralPnlSur, java.awt.BorderLayout.PAGE_END);

        pnlFondo.add(pnlEste, java.awt.BorderLayout.LINE_START);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        Norte.setBackground(new java.awt.Color(18, 18, 18));
        Norte.setPreferredSize(new java.awt.Dimension(962, 32));

        labelNombreUsuario.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        labelNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombreUsuario.setText("User4");

        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
        });

        labelMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_min.png"))); // NOI18N
        labelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout NorteLayout = new javax.swing.GroupLayout(Norte);
        Norte.setLayout(NorteLayout);
        NorteLayout.setHorizontalGroup(
            NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NorteLayout.createSequentialGroup()
                .addContainerGap(671, Short.MAX_VALUE)
                .addComponent(labelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(labelMin)
                .addGap(0, 0, 0)
                .addComponent(labelExit))
        );
        NorteLayout.setVerticalGroup(
            NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorteLayout.createSequentialGroup()
                .addGroup(NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCentro.add(Norte, java.awt.BorderLayout.PAGE_START);

        pnlPrincipal.setBackground(new java.awt.Color(0, 51, 255));
        pnlPrincipal.setLayout(null);
        pnlCentro.add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        Sur.setBackground(new java.awt.Color(40, 40, 40));
        Sur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCentro.add(Sur, java.awt.BorderLayout.PAGE_END);

        pnlFondo.add(pnlCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ExitMousePressed
        this.dispose();
    }//GEN-LAST:event_label_ExitMousePressed

    private void JDAccesosDirectosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JDAccesosDirectosFocusGained

    }//GEN-LAST:event_JDAccesosDirectosFocusGained

    private void label_Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_Exit1MousePressed

    private void JDAccesosDirectos1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JDAccesosDirectos1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JDAccesosDirectos1FocusGained

    private void pnl_TituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TituloMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnl_TituloMousePressed

    private void pnl_TituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TituloMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        this.JDAccesosDirectos.setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_pnl_TituloMouseDragged

    private void labelCancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancionesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCancionesMouseMoved

    private void labelCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancionesMouseClicked
        pnlCanciones pr = new pnlCanciones();
        pr.setSize(dimensiones.getWidt(), dimensiones.getHeig());
        this.pnlPrincipal.removeAll();
        this.pnlPrincipal.add(pr);
        this.pnlPrincipal.revalidate();
        this.pnlPrincipal.repaint();
    }//GEN-LAST:event_labelCancionesMouseClicked

    private void labelCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCancionesMouseExited

    private void labelReproductorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReproductorMouseMoved

    }//GEN-LAST:event_labelReproductorMouseMoved

    private void labelReproductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReproductorMouseClicked
        
    }//GEN-LAST:event_labelReproductorMouseClicked

    private void labelReproductorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReproductorMouseExited

    }//GEN-LAST:event_labelReproductorMouseExited

    private void labelAlbunesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAlbunesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAlbunesMouseMoved

    private void labelAlbunesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAlbunesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAlbunesMouseExited

    private void labelERecienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelERecienteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelERecienteMouseMoved

    private void labelERecienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelERecienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelERecienteMouseExited

    private void labelCFavoritasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCFavoritasMouseMoved

    }//GEN-LAST:event_labelCFavoritasMouseMoved

    private void labelCFavoritasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCFavoritasMouseExited

    }//GEN-LAST:event_labelCFavoritasMouseExited

    private void labelBibliotecaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBibliotecaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBibliotecaMouseMoved

    private void labelBibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBibliotecaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBibliotecaMouseExited

    private void labelListaReproducionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaReproducionesMouseMoved

    }//GEN-LAST:event_labelListaReproducionesMouseMoved

    private void labelListaReproducionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaReproducionesMouseClicked
        pnlListaReproduccion pr = new pnlListaReproduccion();
        pr.setSize(dimensiones.getWidt(), dimensiones.getHeig());
        Artistas art = new Artistas();
        ListRController controlleter = new ListRController(this, art, pr);
        pnlPrincipal.removeAll();
        pnlPrincipal.add(pr);
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
        Sur.updateUI();
    }//GEN-LAST:event_labelListaReproducionesMouseClicked

    private void labelListaReproducionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaReproducionesMouseExited

    }//GEN-LAST:event_labelListaReproducionesMouseExited

    private void lblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaMouseClicked
        
    }//GEN-LAST:event_lblConsultaMouseClicked

    private void labelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_labelMinMouseClicked

    private void labelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinMouseEntered
        labelMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_minh.png"))); // NOI18N
    }//GEN-LAST:event_labelMinMouseEntered

    private void labelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinMouseExited
        labelMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_min.png"))); // NOI18N
    }//GEN-LAST:event_labelMinMouseExited

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exih.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/reproductor/img/ic_exi.png"))); // NOI18N
    }//GEN-LAST:event_labelExitMouseExited

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelUsersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsersMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelUsersMouseMoved

    private void labelUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelUsersMouseExited

    private void labelGeneroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGeneroMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelGeneroMouseMoved

    private void labelGeneroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGeneroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelGeneroMouseExited

    private void labelArtistasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArtistasMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelArtistasMouseMoved

    private void labelArtistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArtistasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelArtistasMouseExited

    private void labelHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelHomeMouseMoved

    private void labelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelHomeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane ContenedorPestanas;
    public javax.swing.JDialog JDAccesosDirectos;
    public javax.swing.JDialog JDAccesosDirectos1;
    public javax.swing.JLabel LabelAccesosR;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JLabel LabelTitulo2;
    private javax.swing.JPanel LateralPnlCentro;
    private javax.swing.JPanel LateralPnlNorte;
    private javax.swing.JPanel LateralPnlSur;
    private javax.swing.JPanel Norte;
    public javax.swing.JPanel Sur;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JPanel fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel labelAlbunes;
    public javax.swing.JLabel labelArtistas;
    public javax.swing.JLabel labelBiblioteca;
    public javax.swing.JLabel labelCFavoritas;
    public javax.swing.JLabel labelCanciones;
    public javax.swing.JLabel labelEReciente;
    public javax.swing.JLabel labelExit;
    public javax.swing.JLabel labelGenero;
    public javax.swing.JLabel labelHome;
    public javax.swing.JLabel labelListaReproduciones;
    private javax.swing.JLabel labelMin;
    public javax.swing.JLabel labelNombreUsuario;
    public javax.swing.JLabel labelReproductor;
    public javax.swing.JLabel labelUsers;
    public javax.swing.JLabel label_Exit;
    public javax.swing.JLabel label_Exit1;
    public javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblYoutube;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlEste;
    private javax.swing.JPanel pnlFondo;
    public javax.swing.JPanel pnlPrincipal;
    public javax.swing.JPanel pnl_Titulo;
    // End of variables declaration//GEN-END:variables
}
